### ISSUE TITLE
missing usernames

### ISSUE THREAD

**Issue by albrox** [joergschultzelutter/enpasstokeepass#2]
For a lot of entries usernames (especially E-Mail) does not get imported. Seems a common issue, as a friend is experiencing the same pretty much

**Comment by joergschultzelutter** [comment]
Sorry for the delayed response - I am completely snowed-under at work. Can you please provide anonymized JSON samples for entries that do not get imported?

I also thought about what to do with fields that cause the import to crash (e.g. your "Title" example) - rather than not importing the field at all, a potential workaround might result in applying a suffix/prefix to the field name, thus allowing it to be imported. Would that be a feasible approach?

**Comment by albrox** [comment]
I guess the suffix/prefix solution sounds good. 
Could you try to use the field "E-Mail", if it throws errors? My workaround was to replace "E-Mail" with "Email"

**Comment by joergschultzelutter** [comment]
Sorry for my delayed response. I did a little bit of experimenting and decided to create Enpass entries for all the possibilities that are natively available through enpass - including all custom field types. I was unable to crash the program in any way - even by using "E-Mail" and "Email" for the same key export. Fields that are part of the red box are custom fields which I added; the one in the green box is the field that come with the native Enpass data set.

![Monosnap 2024-01-02 21-45-47](https://github.com/joergschultzelutter/enpasstokeepass/assets/76180229/6b884f38-bf4d-446d-a2f0-331106dc31c3)

However - when getting exported to Keepass, the green entries' value won't make it to the Keepass database as -due to using the same field name- its value will be overwritten by the one from the red box. Meaning: Field value "E-Mail" will be blah@blub.com" and NOT "add.email@gmail.com". Reason for this is that I simply use the entries "as is" and do not perform a lookup of the entry that is _about_ to be written to keepass. See also the comments related to multiple TOTP entries; it's basically the same thing. Not sure if it's worth being investigated as the export process is usually a one-time thing (and I'd check all entries afterwards nevertheless).

I am going to push a new release to prod in a few minutes. The only major change is that this release now supports enpass tags - there are no other changes. I still encourage you to give this one another try. Please ensure that you have the correct (fixed!) pykeepass lib installed. 

If you still manage to crash the program, please feel free to attach an anonymized json export to this issue ticket so that I can reproduce the issue. Thank you :-)

**Comment by joergschultzelutter** [comment]
Hi - please have a look at [https://github.com/joergschultzelutter/enpasstokeepass/issues/4](https://github.com/joergschultzelutter/enpasstokeepass/issues/4) - I assume that this code fixes your issue. Once confirmed, I will deply a new release. Thank you.

**Comment by joergschultzelutter** [comment]
Fixed as part of [release 1.1](https://github.com/joergschultzelutter/enpasstokeepass/releases/tag/1.1)

**Comment by albrox** [comment]
thanks! :)
